version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: manish
      POSTGRES_PASSWORD: manish
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      REDIS_HOSTNAME: redis
    restart: always
    command: [ "redis-server" ]
  backend:
    container_name: backend
    restart: always
    image: manish09/backend
    depends_on:
      - redis
      - postgres
    ports:
      - 5000:5000
    expose:
      - 5000
  frontend:
    container_name: frontend
    restart: always
    image: manish09/frontend
    depends_on:
      - backend
    ports:
      - 8080:8080
    expose:
      - 8080
