version: "3.8"
services:
  frontend:
    container_name: aymish_frontend
    restart: always
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - backend
  backend:
    container_name: aymish_backend
    restart: always
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 5000:5000
    depends_on:
      - database
      - cache
  database:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=manish
      - POSTGRES_PASSWORD=manish
      - POSTGRES_DB=mydb
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes:
      - ./.postgres-data/postgres:/var/lib/postgresql/data
  cache:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./.redis-data/:/data
      - ./backend/.config/redis.conf/:/redis.conf
    command: ["redis-server", "/redis.conf"]
